# Generated by Django 5.1.3 on 2025-12-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joined',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
