# Generated by Django 6.0.5 on 2026-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_google_id_remove_user_phone_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_sub',
            field=models.CharField(blank=True, null=True),
        ),
    ]
