# Generated by Django 6.0.5 on 2026-07-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='user',
            new_name='author',
        ),
    ]
