# Generated by Django 6.0.5 on 2026-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_checklist_listitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='active_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
