# Generated by Django 6.0.5 on 2026-07-30 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_active_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='co_authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
