# Generated by Django 5.1.3 on 2025-11-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='modified_at',
            new_name='last_modified',
        ),
    ]
